apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app.kubernetes.io/instance: test-label
    app: webapp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: quay.io/pbartczak/flask-app:v1.2
          name: flask-app
          resources:
            requests:
              cpu: "20m"
              memory: "20Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
