apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-env-secret
  namespace: webapp-pipelines
spec:
  encryptedData:
    ARGOCD_AUTH_TOKEN: AgBSXLojXseyvCuzmkJh4JQiz7XidyL9SL+GJzcQduKZbndtW6+G0uwwtvdy8YZ/H6uzNq97BorTKxm2g9RUATMrURtlz5jgXIkIqkMw6tsnD3FmZ7nFk4dAGU05XljIEifzb7oXnprLUXgtJMiQlu4fZIpzrv94zHDhO2/cJEs+Ffi7rjp/FzTgZjKe7fBQKDnWLxRiAzhRUIDDzxtixt9bkds5JrvDX23iEocpspRu31vnXFvANEiyYiRCtbKQFEKe++n2TiF0ouTKm7oAtvAGrP8rpyEcf0D/qnsUxyszQkuUVaOkpwlb7vlGvoYUVf7OwMdVZN5DLtgPEh4xO9rkMXJJrGudrsOvgxc/6eoIazyROavcDKdlQOTS8S+FNPK04+Y+wjd+ZekgKjV6ZX5yRXuzGNSju6+EZL+VoONdtKmF3XoM5vEg3DBucATNI3u4Am7XLUQbXXgclLB9R7rD1OQowDgcqzhY6XhX/wfhcErvIBOVIgVQmEggpzMaSibQyV2Dj9mqVQYgVoBLYSV75nRvNJ4xt6+JiCr2kU++fUVTigP0BUCqDO8XI9pJ/zhDw/b0cOfpduNSMZfUGy8685dPhoJk8FJk38coIsC+EZOwv/aU7Rpw4E/wDp0at5mHo+B9F2d/aSuE3xAU7lLrkXpafsOAv/DsaEdofgSd/SeGc3AQRWBQ4pyUD3/hgD21QNjvbX1kadvyujx5Vv0zmWTSPt1KjN76UnQjU9kmqUSsR41/Mmr85qbBfcAKEpX3/+FKweH7CHqkvo/SK2gW0lIblY/1bY2JnkDTyoEPZt8hlZkjRIjAdfmnVZyNLZrJRY9IquMFdCOCvu4SqXvC1aTX4Z1bToo7yvd7zXubnGNmlrv/LPx/Iklm5rBZeUT/+e87xgGC72rTWsXc+Zll/x8r3vaJBYXn+N3tA//4yBNx+OD+k2hDv3X8TgyfFYE9Di0YQStmT65AEL2Lrddekpz2MP+aq+gwG0B+8SSxzaL7z7lpG6ds7exGp4FEl9FQ2PtUYz6i
  template:
    metadata:
      creationTimestamp: null
      name: argocd-env-secret
      namespace: webapp-pipelines

