apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-webapp-token
  namespace: webapp-pipelines
spec:
  encryptedData:
    password: AgB07EigAn0McqcS7HJJrDuJ4Tl9wJ+PdQ9RJ/ya/Afzf8i+q3pc6KtxwPlBBwqVD1tqR9JbXgUFKBPvY5ckgiWl3IrhVairajfJUnCoWVXt8QkcCY3CiMwStNo20O80Se4z3J90cOLx/Y6sA2fn559Nff0xCZVc1AO13bcZNpgo+mvfotReBfaTGRRA+1FwFVR/hfnP3zTIj7lx6XWPiWDxFeOy6L7c7Z3/7Pfboq6VOk+6zPNHJAsoNIgPuzrSZvx4irLjcL3a7dxgiZ7stnA7TgtaQecOZLKEZ44iD2qsJlMR3Xf2FaliYrynZOpsP0CkIZAVEDhpIL0DKVJ8lRxK+hMHyeGHnBTn/+8lU6SQUwszzhh5w7m+RXdrYVfceeflEKk9264PUfUDyr9xE3zMsz0doOnRodGPbINUT9ccOKeyEIWte09ezNyZ0bZKBRIU7MJtF28YF5VV8ISh38GC2MuuEErOuC7qcEjq04YkXZ3hgsQ4QUyUqL7JnNqlmHIt4dgmGVNKGeYPCoyDdwyPqKimaE07LQoVcHfWlMDyj67Tsp27yoMu1uQTCPKY24T1WpvHNE+l5CHUJMJ3gphKPRBmdhm7RcmnXVi2Cmbv6D1Xp5jwh1ycqgr5MeOy0OIPU+JW2yVT0tPhfQQVMbAf8jz/VGCc4glYP50vJ5qV2oUXEklEiITwRED4Yk/fOacI+LqEebK18vwYEWCxefGhkyoK0WT3yeyXqKHp6K8pWQl9rYVUoEurEmucZLwvyJLco+lAPncII71X9KPcAR2Kdj9agNSO71RrHAXLu05qF/7hYT2yBxtYtCTsjt0=
    username: AgCRzL4kpOrG3JX6ZevCvK5i9sVv5mQ3YfCI3EXnMZfGiAnrCNjSbXX5pGkYiybrzNNUMasWAva8JTiXnmQfsK2roZ6TO4fI1UjY0obBQQ7Rbvq+ErbDfLPcWn+kCUJhsQ2ApAp9vsStPU6hl0NHaWiUgEvXGEarc2jOCeKC/1kzcL0hfuBmbcPHiqQSsjaTvrGmHDOMry+3eAWL9xlXQGJkaFO/R71TAsIexWup/a+sdb+SNizhni68XzAICnbFzjWdgdpiQ19Z5ouutPeFEWMTEL3vM4w2d1IrxL1WgvvZNbZ5T8pxm4/gqVaNdg5jq6SdgtkGk3zp9Dm6CDjI9e2eOuBGj+ML+Smnw7sLl0cqNAzZKuIl/xxiXiShvN8sWPrLohK4hm98+cbMzh3p20iSrjKdWTNLgalH9GIzl5PXz3EO+/8AOnO+NGh7Ay9r/5ZguIZaoh4+s79Vdlrgu76Mbxv/rK1APL7dN5B42cf9CdGWI+Ho4RiYGVwJ/izkONb8rfjGh233kDQGVe0fU2SKV3u6AtEZFKlsL9ue9askz6o94K9ag2ZjbG09UwnN0JS0nMVyUxF9Hbmc81O6u9DXfvF9QyudwGLl6LMr+Ad0wMFXr0lXPS5Nc3hwJPaGGMnWzOy1RyWUXNfktHDj5bxe33ZKlpDcsO/Br0Tsa71bEw/Q/8VZ8ZuERl/Qgd+Qz39smbjAGmM=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-webapp-token
      namespace: webapp-pipelines
    type: kubernetes.io/basic-auth

