---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-deploy-
  namespace: webapp-pipelines
spec:
  pipelineRef:
    name: build-deploy-simple
  serviceAccountName: build-bot
  params:
    - name: buildRevision
      value: "a072bea0e9c17d84ab6cf23893c3108897ba1334"
    - name: appGitUrl
      value: "https://github.com/pbartczak/simple-flask-app.git"
    - name: configGitUrl
      value: "https://github.com/pbartczak/gitops-app-config.git"
    - name: appImage
      value: "quay.io/pbartczak/simple-flask-app"
  workspaces:
    - name: app-source
      emptyDir: {}
    - name: config-source
      emptyDir: {}
