apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: webapp-prod

namePrefix: prod-

commonAnnotations:
  webapp/version: v1

patches:
  - target:
      kind: Deployment
      name: webapp
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/pbartczak/simple-flask-app:ba862531f3165b55a29d90645fc33e63c20e3703

patchesStrategicMerge:
  - |-
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: webapp-route
    spec:
      host: prod-webapp.apps.test.eskom.demo
      to:
        kind: Service
        name: prod-webapp-svc